package DataTransferObject;

import DataAccessObject.DBManager;
import DataAccessObject.DesignDAO;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Entity {
    static Object[][] RAW_MENUS = {
            // 커피 (30개)
            {"커피", "아메리카노", "4,000원", false, "imgpath"},
            {"커피", "카페라떼", "4,500원", true, "imgpath"},
            {"커피", "카푸치노", "5,000원", false, "imgpath"},
            {"커피", "바닐라라떼", "5,000원", false, "imgpath"},
            {"커피", "콜드브루", "5,500원", false, "imgpath"},
            {"커피", "에스프레소", "3,500원", false, "imgpath"},
            {"커피", "돌체라떼", "5,500원", false, "imgpath"},
            {"커피", "헤이즐넛라떼", "5,500원", false, "imgpath"},
            {"커피", "카라멜마끼아또", "5,500원", true, "imgpath"},
            {"커피", "리스트레토", "4,000원", false, "imgpath"},
            {"커피", "롱블랙", "4,000원", false, "imgpath"},
            {"커피", "더치커피", "5,500원", false, "imgpath"},
            {"커피", "콜드브루라떼", "6,000원", false, "imgpath"},
            {"커피", "아인슈페너", "6,000원", false, "imgpath"},
            {"커피", "연유라떼", "5,000원", false, "imgpath"},
            {"커피", "비엔나커피", "5,500원", false, "imgpath"},
            {"커피", "플랫화이트", "5,000원", false, "imgpath"},
            {"커피", "더블샷라떼", "5,500원", false, "imgpath"},
            {"커피", "카페모카", "5,500원", false, "imgpath"},
            {"커피", "흑당라떼", "6,000원", false, "imgpath"},
            {"커피", "토피넛라떼", "5,500원", false, "imgpath"},
            {"커피", "말차라떼", "5,500원", false, "imgpath"},
            {"커피", "코코넛라떼", "5,500원", false, "imgpath"},
            {"커피", "아몬드라떼", "5,500원", false, "imgpath"},
            {"커피", "카라멜라떼", "5,500원", false, "imgpath"},
            {"커피", "콘라떼", "5,500원", false, "imgpath"},
            {"커피", "흑임자라떼", "5,500원", false, "imgpath"},
            {"커피", "모카치노", "5,500원", false, "imgpath"},
            {"커피", "피스타치오라떼", "6,000원", false, "imgpath"},
            {"커피", "스페셜블렌드", "4,000원", false, "imgpath"},

            // 논커피 (30개)
            {"논커피", "딸기라떼", "6,000원", false, "imgpath"},
            {"논커피", "녹차라떼", "6,000원", false, "imgpath"},
            {"논커피", "초코라떼", "6,000원", false, "imgpath"},
            {"논커피", "오렌지주스", "5,000원", false, "imgpath"},
            {"논커피", "유자차", "5,500원", false, "imgpath"},
            {"논커피", "애플주스", "5,000원", false, "imgpath"},
            {"논커피", "복숭아아이스티", "5,000원", false, "imgpath"},
            {"논커피", "레몬차", "5,500원", false, "imgpath"},
            {"논커피", "자몽차", "5,500원", false, "imgpath"},
            {"논커피", "생강차", "5,500원", false, "imgpath"},
            {"논커피", "밀크티", "5,500원", false, "imgpath"},
            {"논커피", "흑당밀크티", "6,000원", false, "imgpath"},
            {"논커피", "블루레몬에이드", "5,500원", false, "imgpath"},
            {"논커피", "망고주스", "6,000원", false, "imgpath"},
            {"논커피", "복숭아주스", "6,000원", false, "imgpath"},
            {"논커피", "청포도주스", "6,000원", false, "imgpath"},
            {"논커피", "크림밀크티", "6,500원", false, "imgpath"},
            {"논커피", "타로밀크티", "6,000원", false, "imgpath"},
            {"논커피", "메론소다", "5,500원", false, "imgpath"},
            {"논커피", "초코쉐이크", "6,000원", false, "imgpath"},
            {"논커피", "딸기주스", "5,500원", false, "imgpath"},
            {"논커피", "코코넛워터", "5,500원", false, "imgpath"},
            {"논커피", "초코우유", "4,000원", false, "imgpath"},
            {"논커피", "홍차", "4,500원", false, "imgpath"},
            {"논커피", "얼그레이", "4,500원", false, "imgpath"},
            {"논커피", "루이보스", "4,500원", false, "imgpath"},
            {"논커피", "캐모마일", "4,500원", false, "imgpath"},
            {"논커피", "보리차", "3,000원", false, "imgpath"},
            {"논커피", "작설차", "4,000원", false, "imgpath"},
            {"논커피", "헛개차", "4,000원", false, "imgpath"},

            // 디저트 (30개)
            {"디저트", "치즈케이크", "7,000원", false, "imgpath"},
            {"디저트", "티라미수", "7,500원", false, "imgpath"},
            {"디저트", "마카롱", "2,000원", true, "imgpath"},
            {"디저트", "쿠키", "1,500원", false, "imgpath"},
            {"디저트", "브라우니", "2,500원", false, "imgpath"},
            {"디저트", "초코케이크", "6,000원", false, "imgpath"},
            {"디저트", "딸기케이크", "6,500원", false, "imgpath"},
            {"디저트", "블루베리타르트", "6,000원", false, "imgpath"},
            {"디저트", "크루아상", "2,000원", false, "imgpath"},
            {"디저트", "머핀", "2,000원", false, "imgpath"},
            {"디저트", "카스테라", "2,000원", false, "imgpath"},
            {"디저트", "에그타르트", "2,500원", false, "imgpath"},
            {"디저트", "도넛", "1,800원", false, "imgpath"},
            {"디저트", "와플", "4,000원", false, "imgpath"},
            {"디저트", "팥빙수", "6,500원", false, "imgpath"},
            {"디저트", "젤라또", "3,500원", false, "imgpath"},
            {"디저트", "요거트", "4,000원", false, "imgpath"},
            {"디저트", "티라미수롤", "5,500원", false, "imgpath"},
            {"디저트", "크림브륄레", "5,000원", false, "imgpath"},
            {"디저트", "슈크림빵", "2,500원", false, "imgpath"},
            {"디저트", "카라멜푸딩", "3,000원", false, "imgpath"},
            {"디저트", "피칸파이", "3,500원", false, "imgpath"},
            {"디저트", "바나나케이크", "4,000원", false, "imgpath"},
            {"디저트", "밤빵", "2,500원", false, "imgpath"},
            {"디저트", "찹쌀떡", "1,500원", false, "imgpath"},
            {"디저트", "에클레어", "3,000원", false, "imgpath"},
            {"디저트", "크레이프", "3,500원", false, "imgpath"},
            {"디저트", "롤케이크", "4,000원", false, "imgpath"},
            {"디저트", "무화과타르트", "4,500원", false, "imgpath"},
            {"디저트", "마들렌", "2,000원", false, "imgpath"},

            // 스무디 (30개)
            {"스무디", "딸기스무디", "6,500원", false, "imgpath"},
            {"스무디", "망고스무디", "6,500원", false, "imgpath"},
            {"스무디", "블루베리스무디", "7,000원", false, "imgpath"},
            {"스무디", "요거트스무디", "6,000원", false, "imgpath"},
            {"스무디", "초코스무디", "6,000원", false, "imgpath"},
            {"스무디", "바나나스무디", "6,000원", false, "imgpath"},
            {"스무디", "딸기바나나", "6,500원", false, "imgpath"},
            {"스무디", "그린티스무디", "6,000원", false, "imgpath"},
            {"스무디", "코코넛스무디", "6,000원", false, "imgpath"},
            {"스무디", "헤이즐넛스무디", "6,000원", false, "imgpath"},
            {"스무디", "복숭아스무디", "6,000원", false, "imgpath"},
            {"스무디", "체리스무디", "6,000원", false, "imgpath"},
            {"스무디", "파인애플스무디", "6,000원", false, "imgpath"},
            {"스무디", "키위스무디", "6,000원", false, "imgpath"},
            {"스무디", "샤인머스캣스무디", "6,500원", false, "imgpath"},
            {"스무디", "망고요거트", "6,500원", false, "imgpath"},
            {"스무디", "스트로베리치즈", "7,000원", false, "imgpath"},
            {"스무디", "민트초코스무디", "6,500원", false, "imgpath"},
            {"스무디", "흑임자스무디", "6,500원", false, "imgpath"},
            {"스무디", "고구마스무디", "6,500원", false, "imgpath"},
            {"스무디", "라즈베리스무디", "6,500원", false, "imgpath"},
            {"스무디", "딸기요거트스무디", "6,500원", false, "imgpath"},
            {"스무디", "블랙체리스무디", "6,500원", false, "imgpath"},
            {"스무디", "라임스무디", "6,500원", false, "imgpath"},
            {"스무디", "애플망고스무디", "6,500원", false, "imgpath"},
            {"스무디", "오렌지스무디", "6,500원", false, "imgpath"},
            {"스무디", "멜론스무디", "6,500원", false, "imgpath"},
            {"스무디", "레몬스무디", "6,500원", false, "imgpath"},
            {"스무디", "청포도스무디", "6,500원", false, "imgpath"},
            {"스무디", "바닐라스무디", "6,500원", false, "imgpath"},

            // 에이드 (30개)
            {"에이드", "레몬에이드", "5,000원", false, "imgpath"},
            {"에이드", "자몽에이드", "5,500원", true, "imgpath"},
            {"에이드", "청포도에이드", "5,500원", false, "imgpath"},
            {"에이드", "오렌지에이드", "5,500원", false, "imgpath"},
            {"에이드", "딸기에이드", "5,500원", false, "imgpath"},
            {"에이드", "복숭아에이드", "5,500원", false, "imgpath"},
            {"에이드", "블루레몬에이드", "5,500원", false, "imgpath"},
            {"에이드", "애플에이드", "5,500원", false, "imgpath"},
            {"에이드", "체리에이드", "5,500원", false, "imgpath"},
            {"에이드", "키위에이드", "5,500원", false, "imgpath"},
            {"에이드", "라임에이드", "5,500원", false, "imgpath"},
            {"에이드", "콜라에이드", "5,000원", false, "imgpath"},
            {"에이드", "사이다에이드", "5,000원", false, "imgpath"},
            {"에이드", "멜론에이드", "5,500원", false, "imgpath"},
            {"에이드", "망고에이드", "5,500원", false, "imgpath"},
            {"에이드", "자두에이드", "5,500원", false, "imgpath"},
            {"에이드", "수박에이드", "5,500원", false, "imgpath"},
            {"에이드", "석류에이드", "5,500원", false, "imgpath"},
            {"에이드", "청귤에이드", "5,500원", false, "imgpath"},
            {"에이드", "샤인머스캣에이드", "5,500원", false, "imgpath"},
            {"에이드", "복숭아복분자에이드", "6,000원", false, "imgpath"},
            {"에이드", "청포도키위에이드", "6,000원", false, "imgpath"},
            {"에이드", "자몽오렌지에이드", "6,000원", false, "imgpath"},
            {"에이드", "레몬청에이드", "6,000원", false, "imgpath"},
            {"에이드", "유자청에이드", "6,000원", false, "imgpath"},
            {"에이드", "딸기라임에이드", "6,000원", false, "imgpath"},
            {"에이드", "자두복숭아에이드", "6,000원", false, "imgpath"},
            {"에이드", "오렌지망고에이드", "6,000원", false, "imgpath"},
            {"에이드", "샤인라임에이드", "6,000원", false, "imgpath"},
            {"에이드", "허니레몬에이드", "6,000원", false, "imgpath"},
    };

    public static final List<Object[]> menus = new ArrayList<>(Arrays.asList(RAW_MENUS));

    public static List<String> categories = new ArrayList<>();

    public static Object[][] designs;
    public static void refreshDesigns() throws Exception {
        try (var conn = DBManager.getInstance().getConnection()) {
            new DesignDAO(conn);
        }
    }
}
